// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: indexv1/index.proto

// Package k4a.index.v1 is the wire contract between a k4a client and the
// shared index daemon (k4a-index). See docs/design/shared-index-service.md.
//
// The service is an accelerator, never a hard dependency: a client that
// cannot reach it falls back to its in-process Tier 1/2/3 search. Every
// response therefore reports *coverage* explicitly so the client makes the
// same index-vs-scan decision it makes locally (local-index.md §Dispatcher),
// and a stale index can never masquerade as current — the client tops up the
// uncovered tail with its own scan.

package indexv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Index_Search_FullMethodName   = "/k4a.index.v1.Index/Search"
	Index_Follow_FullMethodName   = "/k4a.index.v1.Index/Follow"
	Index_Coverage_FullMethodName = "/k4a.index.v1.Index/Coverage"
)

// IndexClient is the client API for Index service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Index is the daemon's query surface.
type IndexClient interface {
	// Search streams a leading Coverage event, then zero or more Match events
	// (newest-first), then a terminal Progress event with done=true. If the
	// topic is not yet followed (and policy allows), the daemon begins
	// following it as a side effect and returns coverage with following=false
	// for this call — the client scans this time, the next call is warm.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchEvent], error)
	// Follow registers a topic without querying it. Used by the client's
	// fire-and-forget warm-up when it scanned a cold topic itself.
	Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error)
	// Coverage reports a topic's indexed ranges without running a query.
	// Used by the Topics view to render an "indexed?" column.
	Coverage(ctx context.Context, in *CoverageRequest, opts ...grpc.CallOption) (*CoverageResponse, error)
}

type indexClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexClient(cc grpc.ClientConnInterface) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Index_ServiceDesc.Streams[0], Index_Search_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SearchRequest, SearchEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Index_SearchClient = grpc.ServerStreamingClient[SearchEvent]

func (c *indexClient) Follow(ctx context.Context, in *FollowRequest, opts ...grpc.CallOption) (*FollowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowResponse)
	err := c.cc.Invoke(ctx, Index_Follow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexClient) Coverage(ctx context.Context, in *CoverageRequest, opts ...grpc.CallOption) (*CoverageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CoverageResponse)
	err := c.cc.Invoke(ctx, Index_Coverage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServer is the server API for Index service.
// All implementations must embed UnimplementedIndexServer
// for forward compatibility.
//
// Index is the daemon's query surface.
type IndexServer interface {
	// Search streams a leading Coverage event, then zero or more Match events
	// (newest-first), then a terminal Progress event with done=true. If the
	// topic is not yet followed (and policy allows), the daemon begins
	// following it as a side effect and returns coverage with following=false
	// for this call — the client scans this time, the next call is warm.
	Search(*SearchRequest, grpc.ServerStreamingServer[SearchEvent]) error
	// Follow registers a topic without querying it. Used by the client's
	// fire-and-forget warm-up when it scanned a cold topic itself.
	Follow(context.Context, *FollowRequest) (*FollowResponse, error)
	// Coverage reports a topic's indexed ranges without running a query.
	// Used by the Topics view to render an "indexed?" column.
	Coverage(context.Context, *CoverageRequest) (*CoverageResponse, error)
	mustEmbedUnimplementedIndexServer()
}

// UnimplementedIndexServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexServer struct{}

func (UnimplementedIndexServer) Search(*SearchRequest, grpc.ServerStreamingServer[SearchEvent]) error {
	return status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedIndexServer) Follow(context.Context, *FollowRequest) (*FollowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Follow not implemented")
}
func (UnimplementedIndexServer) Coverage(context.Context, *CoverageRequest) (*CoverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Coverage not implemented")
}
func (UnimplementedIndexServer) mustEmbedUnimplementedIndexServer() {}
func (UnimplementedIndexServer) testEmbeddedByValue()               {}

// UnsafeIndexServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexServer will
// result in compilation errors.
type UnsafeIndexServer interface {
	mustEmbedUnimplementedIndexServer()
}

func RegisterIndexServer(s grpc.ServiceRegistrar, srv IndexServer) {
	// If the following call pancis, it indicates UnimplementedIndexServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Index_ServiceDesc, srv)
}

func _Index_Search_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IndexServer).Search(m, &grpc.GenericServerStream[SearchRequest, SearchEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Index_SearchServer = grpc.ServerStreamingServer[SearchEvent]

func _Index_Follow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Follow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Index_Follow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Follow(ctx, req.(*FollowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Index_Coverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Coverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Index_Coverage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Coverage(ctx, req.(*CoverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Index_ServiceDesc is the grpc.ServiceDesc for Index service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Index_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k4a.index.v1.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Follow",
			Handler:    _Index_Follow_Handler,
		},
		{
			MethodName: "Coverage",
			Handler:    _Index_Coverage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Search",
			Handler:       _Index_Search_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "indexv1/index.proto",
}
