// SPDX-FileCopyrightText: 2026 Blair Hamilton
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: indexv1/index.proto

// Package k4a.index.v1 is the wire contract between a k4a client and the
// shared index daemon (k4a-index). See docs/design/shared-index-service.md.
//
// The service is an accelerator, never a hard dependency: a client that
// cannot reach it falls back to its in-process Tier 1/2/3 search. Every
// response therefore reports *coverage* explicitly so the client makes the
// same index-vs-scan decision it makes locally (local-index.md §Dispatcher),
// and a stale index can never masquerade as current — the client tops up the
// uncovered tail with its own scan.

package indexv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SearchRequest mirrors the fields the client dispatcher already computed
// (kafka.SearchParams / index.QueryParams) — the regex is passed as its
// source string; scopes name the record fields to match.
type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`                 // regex source; empty = match all
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`                   // any of: "key", "value", "headers"; empty = key+value
	SinceMs       int64                  `protobuf:"varint,4,opt,name=since_ms,json=sinceMs,proto3" json:"since_ms,omitempty"` // Unix millis; 0 = no lower bound
	UntilMs       int64                  `protobuf:"varint,5,opt,name=until_ms,json=untilMs,proto3" json:"until_ms,omitempty"` // Unix millis; 0 = no upper bound
	Partitions    []int32                `protobuf:"varint,6,rep,packed,name=partitions,proto3" json:"partitions,omitempty"`   // empty = all partitions
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`                    // 0 = server default cap
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_indexv1_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SearchRequest) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *SearchRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *SearchRequest) GetSinceMs() int64 {
	if x != nil {
		return x.SinceMs
	}
	return 0
}

func (x *SearchRequest) GetUntilMs() int64 {
	if x != nil {
		return x.UntilMs
	}
	return 0
}

func (x *SearchRequest) GetPartitions() []int32 {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// PartitionCoverage is the indexed offset+time window for one partition —
// the wire form of index.Bookkeeper's per-partition maps.
type PartitionCoverage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	OffsetLo      int64                  `protobuf:"varint,2,opt,name=offset_lo,json=offsetLo,proto3" json:"offset_lo,omitempty"`                  // oldest indexed offset
	OffsetHi      int64                  `protobuf:"varint,3,opt,name=offset_hi,json=offsetHi,proto3" json:"offset_hi,omitempty"`                  // newest indexed offset
	TimestampLoMs int64                  `protobuf:"varint,4,opt,name=timestamp_lo_ms,json=timestampLoMs,proto3" json:"timestamp_lo_ms,omitempty"` // oldest indexed record time (Unix millis)
	TimestampHiMs int64                  `protobuf:"varint,5,opt,name=timestamp_hi_ms,json=timestampHiMs,proto3" json:"timestamp_hi_ms,omitempty"` // newest indexed record time (Unix millis)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionCoverage) Reset() {
	*x = PartitionCoverage{}
	mi := &file_indexv1_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionCoverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionCoverage) ProtoMessage() {}

func (x *PartitionCoverage) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionCoverage.ProtoReflect.Descriptor instead.
func (*PartitionCoverage) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{1}
}

func (x *PartitionCoverage) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *PartitionCoverage) GetOffsetLo() int64 {
	if x != nil {
		return x.OffsetLo
	}
	return 0
}

func (x *PartitionCoverage) GetOffsetHi() int64 {
	if x != nil {
		return x.OffsetHi
	}
	return 0
}

func (x *PartitionCoverage) GetTimestampLoMs() int64 {
	if x != nil {
		return x.TimestampLoMs
	}
	return 0
}

func (x *PartitionCoverage) GetTimestampHiMs() int64 {
	if x != nil {
		return x.TimestampHiMs
	}
	return 0
}

// Gap is a contiguous offset range the daemon knows it did NOT index, so the
// client must not assume coverage across it (mirrors index.Gap).
type Gap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Start         int64                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int64                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gap) Reset() {
	*x = Gap{}
	mi := &file_indexv1_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gap) ProtoMessage() {}

func (x *Gap) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gap.ProtoReflect.Descriptor instead.
func (*Gap) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{2}
}

func (x *Gap) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Gap) GetStart() int64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Gap) GetEnd() int64 {
	if x != nil {
		return x.End
	}
	return 0
}

func (x *Gap) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Coverage is what the index authoritatively holds for a topic at the moment
// the daemon answered. The client compares its query window against this to
// decide covered / partial / uncovered.
type Coverage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partitions    []*PartitionCoverage   `protobuf:"bytes,1,rep,name=partitions,proto3" json:"partitions,omitempty"`
	Gaps          []*Gap                 `protobuf:"bytes,2,rep,name=gaps,proto3" json:"gaps,omitempty"`
	Following     bool                   `protobuf:"varint,3,opt,name=following,proto3" json:"following,omitempty"`     // topic is in the follow-set
	Backfilling   bool                   `protobuf:"varint,4,opt,name=backfilling,proto3" json:"backfilling,omitempty"` // catch-up scan still in progress (window has a moving floor)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coverage) Reset() {
	*x = Coverage{}
	mi := &file_indexv1_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coverage) ProtoMessage() {}

func (x *Coverage) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coverage.ProtoReflect.Descriptor instead.
func (*Coverage) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{3}
}

func (x *Coverage) GetPartitions() []*PartitionCoverage {
	if x != nil {
		return x.Partitions
	}
	return nil
}

func (x *Coverage) GetGaps() []*Gap {
	if x != nil {
		return x.Gaps
	}
	return nil
}

func (x *Coverage) GetFollowing() bool {
	if x != nil {
		return x.Following
	}
	return false
}

func (x *Coverage) GetBackfilling() bool {
	if x != nil {
		return x.Backfilling
	}
	return false
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_indexv1_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Match is one indexed record — the wire form of kafka.ConsumedMessage.
type Match struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Partition     int32                  `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Headers       []*Header              `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Match) Reset() {
	*x = Match{}
	mi := &file_indexv1_index_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Match) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Match) ProtoMessage() {}

func (x *Match) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Match.ProtoReflect.Descriptor instead.
func (*Match) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{5}
}

func (x *Match) GetPartition() int32 {
	if x != nil {
		return x.Partition
	}
	return 0
}

func (x *Match) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Match) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Match) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Match) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Match) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Progress carries the running match count and marks the stream terminal.
type Progress struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Matched int64                  `protobuf:"varint,1,opt,name=matched,proto3" json:"matched,omitempty"`
	Done    bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	// capped reports that more records matched than the request's limit
	// allowed, so the stream carried only the newest page. Without it a
	// truncated answer is indistinguishable from a complete one.
	//
	// An older daemon leaves this at the proto default false, so clients
	// must ALSO infer capping from receiving exactly `limit` matches rather
	// than trusting this field alone.
	Capped        bool `protobuf:"varint,3,opt,name=capped,proto3" json:"capped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_indexv1_index_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{6}
}

func (x *Progress) GetMatched() int64 {
	if x != nil {
		return x.Matched
	}
	return 0
}

func (x *Progress) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Progress) GetCapped() bool {
	if x != nil {
		return x.Capped
	}
	return false
}

// SearchEvent is the streamed union: exactly one field is set per frame.
type SearchEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*SearchEvent_Coverage
	//	*SearchEvent_Match
	//	*SearchEvent_Progress
	Event         isSearchEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchEvent) Reset() {
	*x = SearchEvent{}
	mi := &file_indexv1_index_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchEvent) ProtoMessage() {}

func (x *SearchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchEvent.ProtoReflect.Descriptor instead.
func (*SearchEvent) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{7}
}

func (x *SearchEvent) GetEvent() isSearchEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *SearchEvent) GetCoverage() *Coverage {
	if x != nil {
		if x, ok := x.Event.(*SearchEvent_Coverage); ok {
			return x.Coverage
		}
	}
	return nil
}

func (x *SearchEvent) GetMatch() *Match {
	if x != nil {
		if x, ok := x.Event.(*SearchEvent_Match); ok {
			return x.Match
		}
	}
	return nil
}

func (x *SearchEvent) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Event.(*SearchEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

type isSearchEvent_Event interface {
	isSearchEvent_Event()
}

type SearchEvent_Coverage struct {
	Coverage *Coverage `protobuf:"bytes,1,opt,name=coverage,proto3,oneof"`
}

type SearchEvent_Match struct {
	Match *Match `protobuf:"bytes,2,opt,name=match,proto3,oneof"`
}

type SearchEvent_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

func (*SearchEvent_Coverage) isSearchEvent_Event() {}

func (*SearchEvent_Match) isSearchEvent_Event() {}

func (*SearchEvent_Progress) isSearchEvent_Event() {}

type FollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowRequest) Reset() {
	*x = FollowRequest{}
	mi := &file_indexv1_index_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowRequest) ProtoMessage() {}

func (x *FollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowRequest.ProtoReflect.Descriptor instead.
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{8}
}

func (x *FollowRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

// FollowResponse reports whether the daemon accepted the topic into the
// follow-set. accepted=false with a reason when policy denied it or the
// follow-set is at capacity and all entries are hot.
type FollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowResponse) Reset() {
	*x = FollowResponse{}
	mi := &file_indexv1_index_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowResponse) ProtoMessage() {}

func (x *FollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowResponse.ProtoReflect.Descriptor instead.
func (*FollowResponse) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{9}
}

func (x *FollowResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *FollowResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type CoverageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverageRequest) Reset() {
	*x = CoverageRequest{}
	mi := &file_indexv1_index_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageRequest) ProtoMessage() {}

func (x *CoverageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageRequest.ProtoReflect.Descriptor instead.
func (*CoverageRequest) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{10}
}

func (x *CoverageRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type CoverageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coverage      *Coverage              `protobuf:"bytes,1,opt,name=coverage,proto3" json:"coverage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverageResponse) Reset() {
	*x = CoverageResponse{}
	mi := &file_indexv1_index_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverageResponse) ProtoMessage() {}

func (x *CoverageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexv1_index_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverageResponse.ProtoReflect.Descriptor instead.
func (*CoverageResponse) Descriptor() ([]byte, []int) {
	return file_indexv1_index_proto_rawDescGZIP(), []int{11}
}

func (x *CoverageResponse) GetCoverage() *Coverage {
	if x != nil {
		return x.Coverage
	}
	return nil
}

var File_indexv1_index_proto protoreflect.FileDescriptor

const file_indexv1_index_proto_rawDesc = "" +
	"\n" +
	"\x13indexv1/index.proto\x12\fk4a.index.v1\"\xc3\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x12\x19\n" +
	"\bsince_ms\x18\x04 \x01(\x03R\asinceMs\x12\x19\n" +
	"\buntil_ms\x18\x05 \x01(\x03R\auntilMs\x12\x1e\n" +
	"\n" +
	"partitions\x18\x06 \x03(\x05R\n" +
	"partitions\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\"\xbb\x01\n" +
	"\x11PartitionCoverage\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x1b\n" +
	"\toffset_lo\x18\x02 \x01(\x03R\boffsetLo\x12\x1b\n" +
	"\toffset_hi\x18\x03 \x01(\x03R\boffsetHi\x12&\n" +
	"\x0ftimestamp_lo_ms\x18\x04 \x01(\x03R\rtimestampLoMs\x12&\n" +
	"\x0ftimestamp_hi_ms\x18\x05 \x01(\x03R\rtimestampHiMs\"c\n" +
	"\x03Gap\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x03R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x03R\x03end\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xb2\x01\n" +
	"\bCoverage\x12?\n" +
	"\n" +
	"partitions\x18\x01 \x03(\v2\x1f.k4a.index.v1.PartitionCoverageR\n" +
	"partitions\x12%\n" +
	"\x04gaps\x18\x02 \x03(\v2\x11.k4a.index.v1.GapR\x04gaps\x12\x1c\n" +
	"\tfollowing\x18\x03 \x01(\bR\tfollowing\x12 \n" +
	"\vbackfilling\x18\x04 \x01(\bR\vbackfilling\"0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xb8\x01\n" +
	"\x05Match\x12\x1c\n" +
	"\tpartition\x18\x01 \x01(\x05R\tpartition\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\tR\x05value\x12.\n" +
	"\aheaders\x18\x06 \x03(\v2\x14.k4a.index.v1.HeaderR\aheaders\"P\n" +
	"\bProgress\x12\x18\n" +
	"\amatched\x18\x01 \x01(\x03R\amatched\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x16\n" +
	"\x06capped\x18\x03 \x01(\bR\x06capped\"\xaf\x01\n" +
	"\vSearchEvent\x124\n" +
	"\bcoverage\x18\x01 \x01(\v2\x16.k4a.index.v1.CoverageH\x00R\bcoverage\x12+\n" +
	"\x05match\x18\x02 \x01(\v2\x13.k4a.index.v1.MatchH\x00R\x05match\x124\n" +
	"\bprogress\x18\x03 \x01(\v2\x16.k4a.index.v1.ProgressH\x00R\bprogressB\a\n" +
	"\x05event\"%\n" +
	"\rFollowRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"D\n" +
	"\x0eFollowResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"'\n" +
	"\x0fCoverageRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"F\n" +
	"\x10CoverageResponse\x122\n" +
	"\bcoverage\x18\x01 \x01(\v2\x16.k4a.index.v1.CoverageR\bcoverage2\xdb\x01\n" +
	"\x05Index\x12B\n" +
	"\x06Search\x12\x1b.k4a.index.v1.SearchRequest\x1a\x19.k4a.index.v1.SearchEvent0\x01\x12C\n" +
	"\x06Follow\x12\x1b.k4a.index.v1.FollowRequest\x1a\x1c.k4a.index.v1.FollowResponse\x12I\n" +
	"\bCoverage\x12\x1d.k4a.index.v1.CoverageRequest\x1a\x1e.k4a.index.v1.CoverageResponseB<Z:github.com/blairham/k4a/internal/indexwire/indexv1;indexv1b\x06proto3"

var (
	file_indexv1_index_proto_rawDescOnce sync.Once
	file_indexv1_index_proto_rawDescData []byte
)

func file_indexv1_index_proto_rawDescGZIP() []byte {
	file_indexv1_index_proto_rawDescOnce.Do(func() {
		file_indexv1_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexv1_index_proto_rawDesc), len(file_indexv1_index_proto_rawDesc)))
	})
	return file_indexv1_index_proto_rawDescData
}

var file_indexv1_index_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_indexv1_index_proto_goTypes = []any{
	(*SearchRequest)(nil),     // 0: k4a.index.v1.SearchRequest
	(*PartitionCoverage)(nil), // 1: k4a.index.v1.PartitionCoverage
	(*Gap)(nil),               // 2: k4a.index.v1.Gap
	(*Coverage)(nil),          // 3: k4a.index.v1.Coverage
	(*Header)(nil),            // 4: k4a.index.v1.Header
	(*Match)(nil),             // 5: k4a.index.v1.Match
	(*Progress)(nil),          // 6: k4a.index.v1.Progress
	(*SearchEvent)(nil),       // 7: k4a.index.v1.SearchEvent
	(*FollowRequest)(nil),     // 8: k4a.index.v1.FollowRequest
	(*FollowResponse)(nil),    // 9: k4a.index.v1.FollowResponse
	(*CoverageRequest)(nil),   // 10: k4a.index.v1.CoverageRequest
	(*CoverageResponse)(nil),  // 11: k4a.index.v1.CoverageResponse
}
var file_indexv1_index_proto_depIdxs = []int32{
	1,  // 0: k4a.index.v1.Coverage.partitions:type_name -> k4a.index.v1.PartitionCoverage
	2,  // 1: k4a.index.v1.Coverage.gaps:type_name -> k4a.index.v1.Gap
	4,  // 2: k4a.index.v1.Match.headers:type_name -> k4a.index.v1.Header
	3,  // 3: k4a.index.v1.SearchEvent.coverage:type_name -> k4a.index.v1.Coverage
	5,  // 4: k4a.index.v1.SearchEvent.match:type_name -> k4a.index.v1.Match
	6,  // 5: k4a.index.v1.SearchEvent.progress:type_name -> k4a.index.v1.Progress
	3,  // 6: k4a.index.v1.CoverageResponse.coverage:type_name -> k4a.index.v1.Coverage
	0,  // 7: k4a.index.v1.Index.Search:input_type -> k4a.index.v1.SearchRequest
	8,  // 8: k4a.index.v1.Index.Follow:input_type -> k4a.index.v1.FollowRequest
	10, // 9: k4a.index.v1.Index.Coverage:input_type -> k4a.index.v1.CoverageRequest
	7,  // 10: k4a.index.v1.Index.Search:output_type -> k4a.index.v1.SearchEvent
	9,  // 11: k4a.index.v1.Index.Follow:output_type -> k4a.index.v1.FollowResponse
	11, // 12: k4a.index.v1.Index.Coverage:output_type -> k4a.index.v1.CoverageResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_indexv1_index_proto_init() }
func file_indexv1_index_proto_init() {
	if File_indexv1_index_proto != nil {
		return
	}
	file_indexv1_index_proto_msgTypes[7].OneofWrappers = []any{
		(*SearchEvent_Coverage)(nil),
		(*SearchEvent_Match)(nil),
		(*SearchEvent_Progress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexv1_index_proto_rawDesc), len(file_indexv1_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexv1_index_proto_goTypes,
		DependencyIndexes: file_indexv1_index_proto_depIdxs,
		MessageInfos:      file_indexv1_index_proto_msgTypes,
	}.Build()
	File_indexv1_index_proto = out.File
	file_indexv1_index_proto_goTypes = nil
	file_indexv1_index_proto_depIdxs = nil
}
